### ISSUE TITLE
dissUtils not available for biodivMapR

### ISSUE THREAD

**Issue by jeffyJeff1234** [jbferet/biodivMapR#14]
ERROR: dependency 'dissUtils' is not available for package 'biodivMapR'
.
.
.
.
.installed various versions of R, and still get this error.
even tried with dependencies=TRUE and FALSE, repos=NULL

**Comment by jbferet** [comment]
thank you @jeffyJeff1234 for opeing this issue. 
The package dissUtils was removed from the CRAN. I just pushed a new version using the github repository for dissUtils, which should now work. 
this is in the version 1.9.6

Cheers, 
jb
