### ISSUE TITLE
Dependencies on rgdal and rgeos

### ISSUE THREAD

**Issue by rCarto** [jbferet/biodivMapR#18]
I've heard of this package during a talk in Sageo conf. 
How dependent is it on `rgdal` and `rgeos`?
These packages will retire soon. 
CRAN packages have received these kind of warning : 
https://github.com/riatelab/cartography/issues/85

Detailed post on this matter: [Upcoming changes to popular R packages for spatial data: what you need to do](https://geocompx.org/post/2023/rgdal-retirement/)

You may be well aware of these changes, if so  I am sorry to bother you with this.  

cheers, 

T.

**Comment by jbferet** [comment]
thank you for your suggestion. 
Yes indeed, biodivMapR currently depends on rgdal (GDALinfo, readOGR, writeOGR) and rgeos (gBuffer).
I noticed the warnings you mentioned and this is on my to do list. Multiple parts of the code need to be refreshed, and I am planning on using terra and sf instead of raster, stars and sp. 

This should be done in a next release, hopefully soon!
Thank you for this reminder, this will but these back on the top of the pile. 

cheers,
jb

**Comment by floriandeboissieu** [comment]
I got the following message while doing a `devtools::document()` of the package:
```
ℹ Loading biodivMapR
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
Please note that rgdal will be retired during October 2023,
plan transition to sf/stars/terra functions using GDAL and PROJ
at your earliest convenience.
See https://r-spatial.org/r/2023/05/15/evolution4.html and https://github.com/r-spatial/evolution
rgdal: version: 1.6-7, (SVN revision 1203)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 3.4.1, released 2021/12/27
Path to GDAL shared files: /usr/share/gdal
GDAL binary built with GEOS: TRUE 
Loaded PROJ runtime: Rel. 8.2.1, January 1st, 2022, [PJ_VERSION: 821]
Path to PROJ shared files: /home/boissieu/.local/share/proj:/usr/share/proj
PROJ CDN enabled: TRUE
Linking to sp version:2.0-0
To mute warnings of possible GDAL/OSR exportToProj4() degradation,
use options("rgdal_show_exportToProj4_warnings"="none") before loading sp or rgdal.
```

**Comment by jbferet** [comment]
closing issues as the dependency has been solved. 
thanks @rCarto @floriandeboissieu !
