### ISSUE TITLE
NAs for simpson index

### ISSUE THREAD

**Issue by pijnenburgml** [jbferet/biodivMapR#19]
Dear biodivmapR developers, 

I first came across the issue of getting a map with only 0 as an output of the map_alpha_div for the Simpson index, when running code on my own dataset. What I found strange is that the function output for the Shannon index was resonable, where it seems to me that both index should have been computed from the same baseline data (i.e. I expect to have strange value for both or for none but not for only one of the index output). 

When running your example code with the addition of the Simpson index in the Index_Alpha parameter of the map_alpha_div function I got only NA for the in the Simpson_10 output file, while again a resonable looking output for the Shannon index. 

Is getting NA or 0 for Simpson index a reproducible problem to anyone? 
If so, can we still trust the output for the Shannon index? 

Best, 

Marie-Lou

**Comment by jbferet** [comment]
dear @pijnenburgml , 
thank you for reporting this issue. Indeed, this was a bug which should now be fixed in the latest version (v1.10.5).
Please let us know if this new version actually fixes your problem, or if it still occurs.
best regards, 
Jean-Baptiste
