### ISSUE TITLE
the NAN values exist, it doesn't work

### ISSUE THREAD

**Issue by gig210** [jbferet/biodivMapR#22]
when I performed the model biodivmapR, it did not work, because the NAN values exist. How could I do for this.

**Comment by jbferet** [comment]
Can you please provide more details about your issue? These NaN values may come from improper data preparation or script parameterization, so I cannot tell the problem based on this only input.
- Which type of data are you using?
- did you make sure the HDR file is properly written (including spectral bands for example)?
- are you sure you do not have 0 or negative values in reflectance while trying to apply continuum removal?

If you cannot identify and solve the problem, you will need to send me a subset of your image (after you make sure you can reproduce the error with the subset) and the script producing this error.
Thank you!
Jb

**Comment by gig210** [comment]
Dear Jb,
     I am glad to hear from you. Recently I am studying the α‐ and β‐diversity mapping using remotely sensed images from sentinel-2a, but I failed. Using the samples, I did the experiments. But I cannot do the experiment using our s2a images. I send you a subset of our image and the script resulting in an error. 
   Thank you much.


    Best wishes.










--

*****************************************************
Jianhui Xu  
Guangzhou Institute of Geography 
Guangdong Open Laboratory of Geospatial Information Technology and Application
Key Lab of Guangdong for Utilization of Remote Sensing and Geographical Information System
No. 100 Xianlie Zhong Road, Guangzhou 510070, China 
PostCode：510070
***@***.***
******************************************************




At 2023-09-17 23:57:41, "jbferet" ***@***.***> wrote:

Can you please provide more details on your issue please? These NaN values may come from improper data preparation or script parameterization, so I cannot tell the problem based on this only input.

Which type of data are you using?
did you make sure the HDR file is properly parameterized?
are you sure you do not have 0 or negative values in reflectance while trying to apply continuum removal?

If you cannot identify and solve the problem, I will need you to send me a subset of your image (after you make sure you can reproduce the error with the subset) and the script resulting in an error.
Thank you!
Jb

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
test_subset.zip (30.74M, 2023年10月18日 0:46 到期)
下载

**Comment by jbferet** [comment]
I would need you to send me a link so I can download the subset, as it seems that I cannot access attached file through github

**Comment by gig210** [comment]
Dear Jb,
    I send you the link with baidu :    https://pan.baidu.com/s/1TkNuYog3F93t-uX-LQcnqw, the extract code：3v5u 
    Thanks a lot.




--

*****************************************************
Jianhui Xu  
Guangzhou Institute of Geography 
Guangdong Open Laboratory of Geospatial Information Technology and Application
Key Lab of Guangdong for Utilization of Remote Sensing and Geographical Information System
No. 100 Xianlie Zhong Road, Guangzhou 510070, China 
PostCode：510070
***@***.***
******************************************************




At 2023-09-18 00:59:55, "jbferet" ***@***.***> wrote:

I would need you to send me a link so I can download the subset, as it seems that I cannot access attached file through github

**Comment by jbferet** [comment]
I could not access it, I sent you a message via researchgate!

**Comment by gig210** [comment]
Dear Jb,
      OK, I share it through researchgate.

      Thanks a lots.




--

*****************************************************
Jianhui Xu  
Guangzhou Institute of Geography 
Guangdong Open Laboratory of Geospatial Information Technology and Application
Key Lab of Guangdong for Utilization of Remote Sensing and Geographical Information System
No. 100 Xianlie Zhong Road, Guangzhou 510070, China 
PostCode：510070
***@***.***
******************************************************




At 2023-09-18 01:32:07, "jbferet" ***@***.***> wrote:

I could not access it, I sent you a message via researchgate!

**Comment by jbferet** [comment]
ok I see where your problem is: the reflectance in your image is coded as float between 0 and 1, whereas my tutorials assume that the S2 products correspond to integer (INT16) values with a multiplying factor of 10000. 
then the values for 'Blue_Thresh' and 'NIR_Thresh' should be set accordingly (e.g. Blue_Thresh <- 0.05 instead of Blue_Thresh <- 500), as they are currently set for 10000 factor values. 

Also, I recommend using a window size of minimum 5, as size of 3 will correspond to 9 pixels maximum, which is very low to compare distributions in spectral species.
