### ISSUE TITLE
line 144-149

### ISSUE THREAD

**Issue by LucasXin1** [jbferet/biodivMapR#25]
In line 144-149，which is
Kmeans_info <- map_spectral_species(Input_Image_File = Input_Image_File,
                                    Input_Mask_File = PCA_Output$MaskPath,
                                    Output_Dir = Output_Dir,
                                    SpectralSpace_Output = PCA_Output,
                                    nbclusters = nbclusters,
                                    nbCPU = nbCPU, MaxRAM = MaxRAM)
I met an error:
Error in Subset$DataSubset[, PC_Select] : 
  no 'dimnames' attribute for array
How to solve this problem?

**Comment by jbferet** [comment]
hi @LucasXin1 , 
can you please elaborate? I don't know which script and script lines you are refering to. 
I need you to share your script and data to reproduce the error you mention, or at least a full description of the previous steps. 
thank you
