### ISSUE TITLE
line 133-137

### ISSUE THREAD

**Issue by LucasXin1** [jbferet/biodivMapR#26]
Sel_PC <- select_PCA_components(Input_Image_File = Input_Image_File,
                                Output_Dir = Output_Dir,
                                PCA_Files = PCA_Output$PCA_Files,
                                TypePCA = PCA_Output$TypePCA,
                                File_Open = TRUE)
How can I choose the path? Which path is appropriate?

**Comment by jbferet** [comment]
the path corresponds to the absolute or relative path or the image you want to process. 
PCA_Output is supposed to be produced by the function 'perform_PCA'. 
Please refer to the documentation for additional details.
