### ISSUE TITLE
Error during installing the package

### ISSUE THREAD

**Issue by rrsc1234** [jbferet/biodivMapR#5]
Hi. I have RStudio version 3.5.2 installed in my system. I have downloaded the .zip file of the package and trying to install it using the command: 
<install.packages('C:\\Users\\asd\\Downloads\\biodivMapR-master.zip')> 

After running the above command I am getting the following warning:

"Installing package into ‘C:/Users/asd/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘C:\Users\asd\Downloads\biodivMapR-master.zip’ is not available (for R version 3.5.2)"

Post this when I am trying to import the library(biodivMapR)  I am getting the following:
"Error in library(biodivMapR) : ‘biodivMapR’ is not a valid installed package"

**Comment by floriandeboissieu** [comment]
@rrsc1234 please try the installation with devtools as specified in README (which does not need the pre-download of zip file, it will do it by itself):
```
devtools::install_github('jbferet/biodivMapR')
```
Otherwise, if you still wish to use install.packages, you have to add arguments `, repos=NULL, type="source"`:
```
install.packages('C:\Users\asd\Downloads\biodivMapR-master.zip', repos=NULL, type="source" )
```

**Comment by rrsc1234** [comment]
Hi @floriandeboissieu . I tried your suggestion and tried following command:

< install.packages('C:/Users/asd/Downloads/biodivMapR-master.zip',repos=NULL, type="source") >

After running the above I got the following:

"Installing package into ‘C:/Users/asd/Documents/R/win-library/3.5’ (as ‘lib’ is unspecified)
In R CMD INSTALL",

and a folder named named "biodivMapR-master" is created in the following path:
"C:\Users\asd\Documents\R\win-library\3.5"

Post this after importing the library I am getting:
"Error in library(biodivMapR) : there is no package called ‘biodivMapR’"

**Comment by floriandeboissieu** [comment]
@rrsc1234 have you tried restarting R session before calling `library(biodivMapR)` ?
To do so in Rstudio: menu Session > Restart R

**Comment by rrsc1234** [comment]
@floriandeboissieu. Yes I have restarted my R session also.

**Comment by floriandeboissieu** [comment]
It seems that the package has been wrongly installed the first time and wrongly uninstalled the second time (which often occurs on Windows).

Please, try removing the package manually, i.e. removing directory "C:\Users\asd\Documents\R\win-library\3.5\biodivMapR", and reinstalling with devtools: `devtools::install_git('https://github.com/jbferet/biodivMapR')`
