### ISSUE TITLE
Error Example_script from master Branch

### ISSUE THREAD

**Issue by andreitapch** [jbferet/biodivMapR#6]
Hello, First of all, thanks for sharing the code its really amazing, I was wondering If you could help me with my issue. 
I am running example_script.R but  when is calculating PCA_Output I get an error: 

```
Exclude spectral domains corresponding to water vapor absorption
The following spectral domains (min and max spectral band in nanometers) will be discarded
            [,1] [,2]
Excluded_WL    0  400
             895 1005
            1180 1480
            1780 2040
Please define the input variable Excluded_WL when calling perform_PCA
if you want to modify these spectral domains
[1] "Extract pixels from the images to perform PCA on a subset"
[1] "perform PCA#1 on the subset image"
[1] "Apply PCA model to the whole image"
[1] "PCA Piece # 1 / 1"
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file.
> 
> PCA_Files <- PCA_Output$PCA_Files
Error: object 'PCA_Output' not found
```

After this everything else fails. 

Could you guide me, what I am doing wrong? 
I follow this guide also 
https://jbferet.github.io/biodivMapR/reference/perform_PCA.html

and the difference between (in the tutorial but not in the example) them is:
Excluded_WL <- c(0, 400)
Excluded_WL <- rbind(Excluded_WL, c(895, 1005))
Excluded_WL <- rbind(Excluded_WL, c(1180, 1480))
Excluded_WL <- rbind(Excluded_WL, c(1780, 2040))

Thanks!!

**Comment by jbferet** [comment]
Dear andreitapch, 
thank you for reporting your problem. 
I ran the example_script.R and everything went fine. 

I may need a few additional info from you. 
- can you first reinstall the latest version of the package?
- you will then need to make sure that the data is actually written on your hard drive: when you run the following command "Input_Image_File <- system.file('extdata', 'RASTER', 'S2A_T33NUD_20180104_Subset', package = 'biodivMapR')", can you make sure that the image data is actually written in the path corresponding to "Input_Image_File" , and that you have the right to access it? if previous steps were performed correctly, it should be the case, but just to make sure...
- finally, can you make sure that the package raster is properly installed? can you let me know if the command "r <- brick(Input_Image_File )" runs correctly?

Thank you!

**Comment by CRyan1** [comment]
Hi there, I have the same error as @andreitapch, at exactly the same stage. I've followed the advice given above (all done/ok) and still have the error....(below). Any other suggestions? Thanks :-)
![image](https://user-images.githubusercontent.com/37666111/108457108-c21a3f80-72d6-11eb-8339-985a5335b960.png)
![image](https://user-images.githubusercontent.com/37666111/108457120-cf372e80-72d6-11eb-8ca6-57dbd67c69e4.png)

**Comment by jbferet** [comment]
Hi @andreitapch and @CRyan1 , 
OK, I may have spotted the problem you had. 
I got back to the tutorial, and noticed "TypePCA" was defined after being used in "perform_radiometric_filtering". 

Hence, if you applied the script directly as suggested, this certainly rasied a series of error...

I updatd thee tutorial. This ran on my computer without any problem.
If you still have problems, can you make sure you are using updated versions of the list of packages required in biodivMapR?
If the proble still occurs, I will need you to send me the version installed for each of these packages, and additional information about your R version, OS, etc...

Thank you for reporting this problem, best regards, 

Jean-Baptiste & Florian

    dissUtils,
    data.table,
    ecodist,
    emstreeR,
    fields,
    future,
    future.apply,
    geometry,
    labdsv,
    matlab,
    matrixStats,
    methods,
    mmand,
    raster,
    rgdal,
    R.utils,
    snow,
    sp,
    stars,
    stringr,
    tools,
    vegan,
    zip

**Comment by CRyan1** [comment]
Hi @jbferet,
Thanks for this. I tried the revision and unfortunately I keep getting the same error. I've now also also updated all the packages you recommended but it hasn't made a difference. Below is the list of packages with versions, as requested. I'm running Windows 10 Pro. 
dissUtils,1.0data.table,1.13.6ecodist,2.07emstreeR,2.2.2fields,11.6future,1.21.0future.apply,1.7.0geometry,0.4.5labdsv,2.0.1matlab,1.0.2matrixStats,0.58.0methods,4.0.3mmand,1.6.1raster,3.4-5rgdal,1.5-23R.utils,2.10.1snow,0.4-3sp,1.4-5stars,0.5-1stringr,1.40tools,4.0.3vegan,2.5-7zip, 2.1.1

Thanks again
----

**Comment by jbferet** [comment]
Hi @CRyan1 & @andreitapch , 
thank you or reporting this issue. I followed the advise I gave you, and it appears that the raster package was not up-to-date on my machine... my mistake. The latest version raised this bug you reported. 
I fixed the problem on the latest version of the package. 
The problem actually seemed to occur when TypePCA was set to TRUE. 

Can you please re-install the pakage and give another try with the example script? 

Thanks again for reporting this issue. 

Cheers,

Jean-Baptiste & Florian

**Comment by andreitapch** [comment]
@jbferet 
I was able to use the example script with the latest update! 
Thanks for your help. I really appreciated

**Comment by jbferet** [comment]
@andreitapch 
Marvellous! Thank you again for reporting the problem. I will close the issue, assuming the bug is fixed for @CRyan1 as well. Don't hesitate to contact us again if any other problem with biodivMapR.

**Comment by CRyan1** [comment]
@jbferet   
It works for me now too! I'm excited to use this package with my own data now I know how it's supposed to work. Thanks very much for your help :-)
