### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by CRyan1** [jbferet/biodivMapR#7]
Hi, thanks for making this amazing package - really useful! When installing I get an error that says it's not compatible with R version 4.0.2 or 4.0.3. Could you please let me know which version of R I should use it with? Thanks

**Comment by jbferet** [comment]
Dear CRyan1, 
the latest versions of the package were developed with R v4.0.2. 
I just tested the installation on my computer as specified in the documentation (devtools::install_github('jbferet/biodivMapR')), and this did not raise any error. my personal computer runs with R v4.0.2 as well. 
Also, I am using devtools v2.3.2. 

Can you please send me the full error message raised when attempting to install biodivMapR?

Thank you.

**Comment by CRyan1** [comment]
Hi, it seems it was an issue with my RTools install - all fixed now and the package seems to be working ok. Thanks though!

**Comment by jbferet** [comment]
Great! then I am closing the issue
cheers,
jb
